CREATE TABLE {databaseOwner}SCP_ACCOUNTNUMBERS (ACCOUNTID NUMBER NOT NULL, PORTALID NUMBER(10,0), 
ACCOUNTNUMBER VARCHAR2(50 CHAR) NOT NULL, ACCOUNTNAME VARCHAR2(256 CHAR) NOT NULL,	ACCOUNTDOMAIN 
VARCHAR2(256 CHAR), DESCRIPTION NCLOB, EMAIL1 NVARCHAR2(256) NOT NULL, EMAIL2 NVARCHAR2(256), 
ISENABLED NUMBER(1,0) DEFAULT 1) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_QUESTIONS(QUESTIONID NUMBER, QUESTION NVARCHAR2(2000), LOCALE NVARCHAR2(10)) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_USERPROFILE(PROFILEID NUMBER (10,0) NOT NULL,USERID
NUMBER (10,0) NOT NULL,PROPERTYDEFINITIONID NUMBER (10,0) NOT NULL,PROPERTYVALUE
CLOB  ,PROPERTYTEXT NCLOB  ,VISIBILITY NUMBER (10,0) NOT NULL,LASTUPDATEDDATE
DATE NOT NULL)  TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_USERPROFILE  MODIFY (VISIBILITY DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_CLASSIFICATION(CLASSIFICATIONID NUMBER (10,0)
NOT NULL,CLASSIFICATIONNAME NVARCHAR2 (200) NOT NULL,PARENTID NUMBER (10,0)
) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_EVENTLOGTYPES(LOGTYPEKEY NVARCHAR2 (35) NOT
NULL,LOGTYPEFRIENDLYNAME NVARCHAR2 (50) NOT NULL,LOGTYPEDESCRIPTION NVARCHAR2
(128),LOGTYPEOWNER NVARCHAR2 (100) NOT NULL,LOGTYPECSSCLASS NVARCHAR2
(40) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_EVENTLOGCONFIG(ID NUMBER (10,0) NOT NULL,LOGTYPEKEY
NVARCHAR2 (35)  ,LOGTYPEPORTALID NUMBER (10,0)  ,LOGGINGISACTIVE NUMBER
(1,0) NOT NULL,KEEPMOSTRECENT NUMBER (10,0) NOT NULL,EMAILNOTIFICATIONISACTIVE
NUMBER (1,0)  ,NOTIFICATIONTHRESHOLD NUMBER (10,0)  ,NOTIFICATIONTHRESHOLDTIME
NUMBER (10,0)  ,NOTIFICATIONTHRESHOLDTIMETYPE NUMBER (10,0)  ,MAILFROMADDRESS
NVARCHAR2 (50),MAILTOADDRESS NVARCHAR2 (50)) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_LISTS(ENTRYID NUMBER (10,0) NOT NULL,LISTNAME
NVARCHAR2 (50) NOT NULL,VALUE NVARCHAR2 (100) NOT NULL,TEXT NVARCHAR2
(150) NOT NULL,PARENTID NUMBER (10,0) NOT NULL,LEVEL_ NUMBER (10,0) NOT
NULL,SORTORDER NUMBER (10,0) NOT NULL,DEFINITIONID NUMBER (10,0) NOT NULL,DESCRIPTION
NVARCHAR2 (500)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_LISTS  MODIFY (PARENTID DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_LISTS  MODIFY (LEVEL_ DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_LISTS  MODIFY (SORTORDER DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_LISTS  MODIFY (DEFINITIONID DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_USERS(USERID NUMBER (10,0) NOT NULL,USERNAME
NVARCHAR2 (100) NOT NULL,FIRSTNAME NVARCHAR2 (50) NOT NULL,LASTNAME NVARCHAR2
(50) NOT NULL,ISSUPERUSER NUMBER (1,0) NOT NULL,AFFILIATEID NUMBER (10,0)
,EMAIL NVARCHAR2 (256)  ,DISPLAYNAME NVARCHAR2 (128),UPDATEPASSWORD
NUMBER (1,0), ACCOUNTID NUMBER  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_USERS  MODIFY (ISSUPERUSER DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_USERS  MODIFY (UPDATEPASSWORD DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_SEARCHITEM(SEARCHITEMID NUMBER (10,0) NOT NULL,TITLE
NVARCHAR2 (200) NOT NULL,DESCRIPTION NVARCHAR2 (2000) NOT NULL,AUTHOR
NUMBER (10,0)  ,PUBDATE DATE NOT NULL,MODULEID NUMBER (10,0) NOT NULL,SEARCHKEY
NVARCHAR2 (100)  ,GUID VARCHAR2 (200)  ,HITCOUNT NUMBER (10,0)
,IMAGEFILEID NUMBER (10,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_VENDORCLASSIFICATION(VENDORCLASSIFICATIONID
NUMBER (10,0) NOT NULL,VENDORID NUMBER (10,0) NOT NULL,CLASSIFICATIONID
NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_PORTALDESKTOPMODULES(PORTALDESKTOPMODULEID NUMBER
(10,0) NOT NULL,PORTALID NUMBER (10,0) NOT NULL,DESKTOPMODULEID NUMBER
(10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_BANNERS(BANNERID NUMBER (10,0) NOT NULL,VENDORID
NUMBER (10,0) NOT NULL,IMAGEFILE NVARCHAR2 (100)  ,BANNERNAME NVARCHAR2
(100) NOT NULL,IMPRESSIONS NUMBER (10,0) NOT NULL,CPM FLOAT (53) NOT NULL,VIEWS
NUMBER (10,0) NOT NULL,CLICKTHROUGHS NUMBER (10,0) NOT NULL,STARTDATE
DATE  ,ENDDATE DATE  ,CREATEDBYUSER NVARCHAR2 (100) NOT NULL,CREATEDDATE
DATE NOT NULL,BANNERTYPEID NUMBER (10,0)  ,DESCRIPTION NVARCHAR2 (2000)
,GROUPNAME NVARCHAR2 (100)  ,CRITERIA NUMBER (1,0) NOT NULL,URL NVARCHAR2
(255)  ,WIDTH NUMBER (10,0) NOT NULL,HEIGHT NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_BANNERS  MODIFY (VIEWS DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_BANNERS  MODIFY (CLICKTHROUGHS DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_BANNERS  MODIFY (CRITERIA DEFAULT (1))
/
ALTER TABLE {databaseOwner}SCP_BANNERS  MODIFY (WIDTH DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_BANNERS  MODIFY (HEIGHT DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_PORTALALIAS(PORTALALIASID NUMBER (10,0) NOT
NULL,PORTALID NUMBER (10,0) NOT NULL,HTTPALIAS NVARCHAR2 (200)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_USERROLES(USERROLEID NUMBER (10,0) NOT NULL,USERID
NUMBER (10,0) NOT NULL,ROLEID NUMBER (10,0) NOT NULL,EXPIRYDATE DATE 
,ISTRIALUSED NUMBER (1,0)  ,EFFECTIVEDATE DATE  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SCHEDULEITEMSETTINGS(SCHEDULEID NUMBER (10,0)
NOT NULL,SETTINGNAME NVARCHAR2 (50) NOT NULL,SETTINGVALUE NVARCHAR2 (256)
NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_VENDORS(VENDORID NUMBER (10,0) NOT NULL,VENDORNAME
NVARCHAR2 (50) NOT NULL,STREET NVARCHAR2 (50)  ,CITY NVARCHAR2 (50)  ,REGION
NVARCHAR2 (50)  ,COUNTRY NVARCHAR2 (50)  ,POSTALCODE NVARCHAR2 (50)  ,TELEPHONE
NVARCHAR2 (50)  ,PORTALID NUMBER (10,0)  ,FAX NVARCHAR2 (50)  ,EMAIL NVARCHAR2
(50)  ,WEBSITE NVARCHAR2 (100)  ,CLICKTHROUGHS NUMBER (10,0) NOT NULL,VIEWS
NUMBER (10,0) NOT NULL,CREATEDBYUSER NVARCHAR2 (100)  ,CREATEDDATE DATE
,LOGOFILE NVARCHAR2 (100)  ,KEYWORDS NCLOB  ,UNIT NVARCHAR2 (50)  ,AUTHORIZED
NUMBER (1,0) NOT NULL,FIRSTNAME NVARCHAR2 (50)  ,LASTNAME NVARCHAR2 (50)
,CELL VARCHAR2 (50)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_VENDORS  MODIFY (CLICKTHROUGHS DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_VENDORS  MODIFY (VIEWS DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_VENDORS  MODIFY (AUTHORIZED DEFAULT (1))
/

CREATE TABLE {databaseOwner}SCP_PROFILEPROPERTYDEFINITION(PROPERTYDEFINITIONID
NUMBER (10,0) NOT NULL,PORTALID NUMBER (10,0)  ,MODULEDEFID NUMBER (10,0)
,DELETED NUMBER (1,0) NOT NULL,DATATYPE NUMBER (10,0) NOT NULL,DEFAULTVALUE
NVARCHAR2 (50)  ,PROPERTYCATEGORY NVARCHAR2 (50) NOT NULL,PROPERTYNAME
NVARCHAR2 (50) NOT NULL,LENGTH NUMBER (10,0) NOT NULL,REQUIRED NUMBER
(1,0)  ,VALIDATIONEXPRESSION NVARCHAR2 (2000)  ,VIEWORDER NUMBER (10,0)
NOT NULL,VISIBLE NUMBER (1,0),SEARCHABLE NUMBER (1,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_PROFILEPROPERTYDEFINITION  MODIFY (LENGTH DEFAULT(0))
/

CREATE TABLE {databaseOwner}SCP_PORTALS(PORTALID NUMBER (10,0) NOT NULL,PORTALNAME
NVARCHAR2 (128) NOT NULL,LOGOFILE NVARCHAR2 (50)  ,FOOTERTEXT NVARCHAR2
(100)  ,EXPIRYDATE DATE  ,USERREGISTRATION NUMBER (10,0) NOT NULL,BANNERADVERTISING
NUMBER (10,0) NOT NULL,ADMINISTRATORID NUMBER (10,0)  ,CURRENCY CHAR (3)
,HOSTFEE NUMBER (19,4) NOT NULL,HOSTSPACE NUMBER (10,0) NOT NULL,ADMINISTRATORROLEID
NUMBER (10,0)  ,POWERUSERROLEID NUMBER (10,0),   REGISTEREDROLEID NUMBER (10,0)  ,DESCRIPTION NVARCHAR2
(500)  ,KEYWORDS NVARCHAR2 (500)  ,BACKGROUNDFILE NVARCHAR2 (50)  ,GUID
NVARCHAR2(51) NOT NULL,PAYMENTPROCESSOR NVARCHAR2 (50)  ,PROCESSORUSERID NVARCHAR2
(50)  ,PROCESSORPASSWORD NVARCHAR2 (50)  ,SITELOGHISTORY NUMBER (10,0)
,HOMETABID NUMBER (10,0)  ,LOGINTABID NUMBER (10,0)  ,USERTABID NUMBER
(10,0)  ,DEFAULTLANGUAGE NVARCHAR2 (10) NOT NULL,TIMEZONEOFFSET NUMBER
(10,0) NOT NULL,ADMINTABID NUMBER (10,0)  ,HOMEDIRECTORY VARCHAR2 (100)
,SPLASHTABID NUMBER (10,0)  ,PAGEQUOTA NUMBER (10,0) NOT NULL,USERQUOTA
NUMBER (10,0) NOT NULL, ADMINACCOUNTID NUMBER(10, 0)) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (USERREGISTRATION DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (BANNERADVERTISING DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (HOSTFEE DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (HOSTSPACE DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (DEFAULTLANGUAGE DEFAULT ('en-US'))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (TIMEZONEOFFSET DEFAULT ((-8)))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (HOMEDIRECTORY DEFAULT (' '))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (PAGEQUOTA DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (USERQUOTA DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_PORTALS  MODIFY (GUID DEFAULT (SYS_GUID()))
/

CREATE TABLE {databaseOwner}SCP_ROLEGROUPS(ROLEGROUPID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0) NOT NULL,ROLEGROUPNAME NVARCHAR2 (50) NOT NULL,DESCRIPTION
NVARCHAR2 (1000)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SEARCHCOMMONWORDS(COMMONWORDID NUMBER (10,0)
NOT NULL,COMMONWORD NVARCHAR2 (255) NOT NULL,LOCALE NVARCHAR2 (10)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_DESKTOPMODULES(DESKTOPMODULEID NUMBER (10,0)
NOT NULL,FRIENDLYNAME NVARCHAR2 (128) NOT NULL,DESCRIPTION NVARCHAR2 (2000)
,VERSION NVARCHAR2 (8) ,ISPREMIUM NUMBER (1,0) NOT NULL,ISADMIN NUMBER
(1,0)  ,BUSINESSCONTROLLERCLASS NVARCHAR2 (200)  ,FOLDERNAME NVARCHAR2
(128) NOT NULL,MODULENAME NVARCHAR2 (128) NOT NULL,SUPPORTEDFEATURES NUMBER
(10,0) NOT NULL,COMPATIBLEVERSIONS NVARCHAR2 (500)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_DESKTOPMODULES  MODIFY (SUPPORTEDFEATURES DEFAULT(0))
/

CREATE TABLE {databaseOwner}SCP_SKINS(SKINID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0)  ,SKINROOT NVARCHAR2 (50) NOT NULL,SKINSRC NVARCHAR2 (200)
NOT NULL,SKINTYPE NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_MODULESETTINGS(MODULEID NUMBER (10,0) NOT NULL,SETTINGNAME
NVARCHAR2 (50) NOT NULL,SETTINGVALUE NVARCHAR2 (2000)) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SEARCHWORD(SEARCHWORDSID NUMBER (10,0) NOT NULL,WORD
NVARCHAR2 (100) NOT NULL,ISCOMMON NUMBER (1,0)  ,HITCOUNT NUMBER (10,0)
NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_TABPERMISSION(TABPERMISSIONID NUMBER (10,0)
NOT NULL,TABID NUMBER (10,0) NOT NULL,PERMISSIONID NUMBER (10,0) NOT NULL,ROLEID
NUMBER (10,0) NOT NULL,ALLOWACCESS NUMBER (1,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_MODULECONTROLS(MODULECONTROLID NUMBER (10,0)
NOT NULL,MODULEDEFID NUMBER (10,0)  ,CONTROLKEY NVARCHAR2 (50)  ,CONTROLTITLE
NVARCHAR2 (50)  ,CONTROLSRC NVARCHAR2 (256)  ,ICONFILE NVARCHAR2 (100)
,CONTROLTYPE NUMBER (10,0) NOT NULL,VIEWORDER NUMBER (10,0)  ,HELPURL
NVARCHAR2 (200)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_TABMODULES(TABMODULEID NUMBER (10,0) NOT NULL,TABID
NUMBER (10,0) NOT NULL,MODULEID NUMBER (10,0) NOT NULL,PANENAME NVARCHAR2
(50) NOT NULL,MODULEORDER NUMBER (10,0) NOT NULL,CACHETIME NUMBER (10,0)
NOT NULL,ALIGNMENT NVARCHAR2 (10)  ,COLOR NVARCHAR2 (20)  ,BORDER NVARCHAR2
(1)  ,ICONFILE NVARCHAR2 (100)  ,VISIBILITY NUMBER (10,0) NOT NULL,CONTAINERSRC
NVARCHAR2 (200)  ,DISPLAYTITLE NUMBER (1,0) NOT NULL,DISPLAYPRINT NUMBER
(1,0)  ,DISPLAYSYNDICATE NUMBER (1,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_TABMODULES  MODIFY (DISPLAYTITLE DEFAULT (1))
/
ALTER TABLE {databaseOwner}SCP_TABMODULES  MODIFY (DISPLAYPRINT DEFAULT (1))
/
ALTER TABLE {databaseOwner}SCP_TABMODULES  MODIFY (DISPLAYSYNDICATE DEFAULT
(1))
/

CREATE TABLE {databaseOwner}SCP_MODULEDEFINITIONS(MODULEDEFID NUMBER (10,0)
NOT NULL,FRIENDLYNAME NVARCHAR2 (128) NOT NULL,DESKTOPMODULEID NUMBER
(10,0) NOT NULL,DEFAULTCACHETIME NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_MODULEDEFINITIONS  MODIFY (DEFAULTCACHETIME DEFAULT(0))
/

CREATE TABLE {databaseOwner}SCP_ANONYMOUSUSERS(USERID CHAR (36) NOT NULL,PORTALID
NUMBER (10,0) NOT NULL,TABID NUMBER (10,0) NOT NULL,CREATIONDATE DATE
NOT NULL,LASTACTIVEDATE DATE NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_ANONYMOUSUSERS  MODIFY (CREATIONDATE DEFAULT
(SYSDATE))
/
ALTER TABLE {databaseOwner}SCP_ANONYMOUSUSERS  MODIFY (LASTACTIVEDATE DEFAULT
(SYSDATE))
/

CREATE TABLE {databaseOwner}SCP_FOLDERPERMISSION(FOLDERPERMISSIONID NUMBER (10,0)
NOT NULL,FOLDERID NUMBER (10,0) NOT NULL,PERMISSIONID NUMBER (10,0) NOT
NULL,ROLEID NUMBER (10,0) NOT NULL,ALLOWACCESS NUMBER (1,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SEARCHITEMWORDPOSITION(SEARCHITEMWORDPOSITIONID
NUMBER (10,0) NOT NULL,SEARCHITEMWORDID NUMBER (10,0) NOT NULL,CONTENTPOSITION
NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_TABMODULESETTINGS(TABMODULEID NUMBER (10,0)
NOT NULL,SETTINGNAME NVARCHAR2 (50) NOT NULL,SETTINGVALUE NVARCHAR2 (2000)) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_EVENTLOG(LOGGUID VARCHAR2 (36) NOT NULL,LOGTYPEKEY
NVARCHAR2 (35) NOT NULL,LOGCONFIGID NUMBER (10,0)  ,LOGUSERID NUMBER (10,0)
,LOGUSERNAME NVARCHAR2 (50)  ,LOGPORTALID NUMBER (10,0)  ,LOGPORTALNAME
NVARCHAR2 (100)  ,LOGCREATEDATE DATE NOT NULL,LOGSERVERNAME NVARCHAR2
(50) NOT NULL,LOGPROPERTIES NCLOB NOT NULL,LOGNOTIFICATIONPENDING NUMBER
(1,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SITELOG(SITELOGID NUMBER (10,0) NOT NULL,DATETIME
DATE NOT NULL,PORTALID NUMBER (10,0) NOT NULL,USERID NUMBER (10,0)  ,REFERRER
NVARCHAR2 (255)  ,URL NVARCHAR2 (255)  ,USERAGENT NVARCHAR2 (255)  ,USERHOSTADDRESS
NVARCHAR2 (255)  ,USERHOSTNAME NVARCHAR2 (255)  ,TABID NUMBER (10,0) 
,AFFILIATEID NUMBER (10,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/


DECLARE 
  v_exists NUMBER(1,0);
BEGIN

  v_exists := 0;
  SELECT COUNT(*)
  INTO v_exists
  FROM user_tables
  WHERE LOWER(TABLE_NAME) = LOWER('SCP_VERSION');

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {databaseOwner}SCP_VERSION(VERSIONID NUMBER (10,0) NOT NULL,MAJOR
		NUMBER (10,0) NOT NULL,MINOR NUMBER (10,0) NOT NULL,BUILD NUMBER (10,0)
		NOT NULL,CREATEDDATE DATE NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K';
  END IF;
END;
/

CREATE TABLE {databaseOwner}SCP_SCHEDULE(SCHEDULEID NUMBER (10,0) NOT NULL,TYPEFULLNAME
VARCHAR2 (200) NOT NULL,TIMELAPSE NUMBER (10,0) NOT NULL,TIMELAPSEMEASUREMENT
VARCHAR2 (2) NOT NULL,RETRYTIMELAPSE NUMBER (10,0) NOT NULL,RETRYTIMELAPSEMEASUREMENT
VARCHAR2 (2) NOT NULL,RETAINHISTORYNUM NUMBER (10,0) NOT NULL,ATTACHTOEVENT
VARCHAR2 (50),CATCHUPENABLED NUMBER (1,0) NOT NULL,ENABLED NUMBER
(1,0)  ,OBJECTDEPENDENCIES VARCHAR2 (300),SERVERS NVARCHAR2 (150)) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_FOLDERS(FOLDERID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0)  ,FOLDERPATH VARCHAR2 (300),STORAGELOCATION NUMBER
(10,0) NOT NULL,ISPROTECTED NUMBER (1,0) NOT NULL,ISCACHED NUMBER (1,0)
,LASTUPDATED DATE  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_FOLDERS  MODIFY (STORAGELOCATION DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_FOLDERS  MODIFY (ISPROTECTED DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_FOLDERS  MODIFY (ISCACHED DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_SEARCHINDEXER(SEARCHINDEXERID NUMBER (10,0)
NOT NULL,SEARCHINDEXERASSEMBLYQUALIFIED CHAR (200) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_HOSTSETTINGS(SETTINGNAME NVARCHAR2 (50) NOT
NULL,SETTINGVALUE NVARCHAR2 (256),SETTINGISSECURE NUMBER (1,0)
NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_HOSTSETTINGS  MODIFY (SETTINGISSECURE DEFAULT
(0))
/

CREATE TABLE {databaseOwner}SCP_URLLOG(URLLOGID NUMBER (10,0) NOT NULL,URLTRACKINGID
NUMBER (10,0) NOT NULL,CLICKDATE DATE NOT NULL,USERID NUMBER (10,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_MODULES(MODULEID NUMBER (10,0) NOT NULL,MODULEDEFID
NUMBER (10,0) NOT NULL,MODULETITLE NVARCHAR2 (256)  ,ALLTABS NUMBER (1,0)
NOT NULL,ISDELETED NUMBER (1,0)  ,INHERITVIEWPERMISSIONS NUMBER (1,0)
,HEADER NCLOB  ,FOOTER NCLOB  ,STARTDATE DATE  ,ENDDATE DATE  ,PORTALID
NUMBER (10,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_MODULES  MODIFY (ALLTABS DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_MODULES  MODIFY (ISDELETED DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_SYSTEMMESSAGES(MESSAGEID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0)  ,MESSAGENAME NVARCHAR2 (50) NOT NULL,MESSAGEVALUE NCLOB
NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_USERPORTALS(USERID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0) NOT NULL,USERPORTALID NUMBER (10,0) NOT NULL,CREATEDDATE
DATE NOT NULL,AUTHORISED NUMBER (1,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_USERPORTALS  MODIFY (CREATEDDATE DEFAULT (SYSDATE))
/
ALTER TABLE {databaseOwner}SCP_USERPORTALS  MODIFY (AUTHORISED DEFAULT (1))
/

CREATE TABLE {databaseOwner}SCP_ROLES(ROLEID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0) NOT NULL,ROLENAME NVARCHAR2 (50) NOT NULL,DESCRIPTION NVARCHAR2
(1000)  ,SERVICEFEE NUMBER (19,4)  ,BILLINGFREQUENCY CHAR (1)  ,TRIALPERIOD
NUMBER (10,0)  ,TRIALFREQUENCY CHAR (1)  ,BILLINGPERIOD NUMBER (10,0)
,TRIALFEE NUMBER (19,4)  ,ISPUBLIC NUMBER (1,0) NOT NULL,AUTOASSIGNMENT
NUMBER (1,0)  ,ROLEGROUPID NUMBER (10,0)  ,RSVPCODE NVARCHAR2 (50)  ,ICONFILE
NVARCHAR2 (100)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_ROLES  MODIFY (SERVICEFEE DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_ROLES  MODIFY (ISPUBLIC DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_ROLES  MODIFY (AUTOASSIGNMENT DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_PROFILE(PROFILEID NUMBER (10,0) NOT NULL,USERID
NUMBER (10,0) NOT NULL,PORTALID NUMBER (10,0) NOT NULL,PROFILEDATA NCLOB,
CREATEDDATE DATE NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_PERMISSION(PERMISSIONID NUMBER (10,0) NOT NULL,PERMISSIONCODE
VARCHAR2 (50) NOT NULL,MODULEDEFID NUMBER (10,0) NOT NULL,PERMISSIONKEY
VARCHAR2 (20) NOT NULL,PERMISSIONNAME VARCHAR2 (50) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_FILES(FILEID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0)  ,FILENAME NVARCHAR2 (100) NOT NULL,EXTENSION NVARCHAR2
(100) NOT NULL,SIZE_ NUMBER (10,0) NOT NULL,WIDTH NUMBER (10,0)  ,HEIGHT
NUMBER (10,0)  ,CONTENTTYPE NVARCHAR2 (200) NOT NULL,FOLDER NVARCHAR2
(200)  ,FOLDERID NUMBER (10,0) NOT NULL,CONTENT BLOB  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_AFFILIATES(AFFILIATEID NUMBER (10,0) NOT NULL,VENDORID
NUMBER (10,0)  ,STARTDATE DATE  ,ENDDATE DATE  ,CPC FLOAT (53) NOT NULL,CLICKS
NUMBER (10,0) NOT NULL,CPA FLOAT (53) NOT NULL,ACQUISITIONS NUMBER (10,0)
NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_SCHEDULEHISTORY(SCHEDULEHISTORYID NUMBER (10,0)
NOT NULL,SCHEDULEID NUMBER (10,0) NOT NULL,STARTDATE DATE NOT NULL,ENDDATE
DATE  ,SUCCEEDED NUMBER (1,0)  ,LOGNOTES NCLOB  ,NEXTSTART DATE  ,SERVER
NVARCHAR2 (150)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_MODULEPERMISSION(MODULEPERMISSIONID NUMBER (10,0)
NOT NULL,MODULEID NUMBER (10,0) NOT NULL,PERMISSIONID NUMBER (10,0) NOT
NULL,ROLEID NUMBER (10,0) NOT NULL,ALLOWACCESS NUMBER (1,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_TABS(TABID NUMBER (10,0) NOT NULL,TABORDER NUMBER
(10,0) NOT NULL,PORTALID NUMBER (10,0)  ,TABNAME NVARCHAR2 (50) NOT NULL,ISVISIBLE
NUMBER (1,0) NOT NULL,PARENTID NUMBER (10,0)  ,LEVEL_ NUMBER (10,0) NOT
NULL,ICONFILE NVARCHAR2 (100)  ,DISABLELINK NUMBER (1,0)  ,TITLE NVARCHAR2
(200)  ,DESCRIPTION NVARCHAR2 (500)  ,KEYWORDS NVARCHAR2 (500)  ,ISDELETED
NUMBER (1,0)  ,URL NVARCHAR2 (255)  ,SKINSRC NVARCHAR2 (200)  ,CONTAINERSRC
NVARCHAR2 (200)  ,TABPATH NVARCHAR2 (255)  ,STARTDATE DATE  ,ENDDATE DATE
,REFRESHINTERVAL NUMBER (10,0)  ,PAGEHEADTEXT NVARCHAR2 (500)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_TABS  MODIFY (TABORDER DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_TABS  MODIFY (ISVISIBLE DEFAULT (1))
/
ALTER TABLE {databaseOwner}SCP_TABS  MODIFY (LEVEL_ DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_TABS  MODIFY (DISABLELINK DEFAULT (0))
/
ALTER TABLE {databaseOwner}SCP_TABS  MODIFY (ISDELETED DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_URLTRACKING(URLTRACKINGID NUMBER (10,0) NOT
NULL,PORTALID NUMBER (10,0)  ,URL NVARCHAR2 (255) NOT NULL,URLTYPE CHAR
(1) NOT NULL,CLICKS NUMBER (10,0) NOT NULL,LASTCLICK DATE  ,CREATEDDATE
DATE NOT NULL,LOGACTIVITY NUMBER (1,0) NOT NULL,TRACKCLICKS NUMBER (1,0)
,MODULEID NUMBER (10,0)  ,NEWWINDOW NUMBER (1,0)  ) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_URLTRACKING  MODIFY (TRACKCLICKS DEFAULT (1))
/
ALTER TABLE {databaseOwner}SCP_URLTRACKING  MODIFY (NEWWINDOW DEFAULT (0))
/

CREATE TABLE {databaseOwner}SCP_URLS(URLID NUMBER (10,0) NOT NULL,PORTALID NUMBER
(10,0)  ,URL NVARCHAR2 (255) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

CREATE TABLE {databaseOwner}SCP_USERSONLINE(USERID NUMBER (10,0) NOT NULL,PORTALID
NUMBER (10,0) NOT NULL,TABID NUMBER (10,0) NOT NULL,CREATIONDATE DATE
NOT NULL,LASTACTIVEDATE DATE NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/

ALTER TABLE {databaseOwner}SCP_USERSONLINE  MODIFY (CREATIONDATE DEFAULT (SYSDATE))
/
ALTER TABLE {databaseOwner}SCP_USERSONLINE  MODIFY (LASTACTIVEDATE DEFAULT (SYSDATE))
/

CREATE TABLE {databaseOwner}SCP_SEARCHITEMWORD(SEARCHITEMWORDID NUMBER (10,0)
NOT NULL,SEARCHITEMID NUMBER (10,0) NOT NULL,SEARCHWORDSID NUMBER (10,0)
NOT NULL,OCCURRENCES NUMBER (10,0) NOT NULL) TABLESPACE CSWS_DBO_DATA01_128K
/
